name: Build and deploy with Node.js 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Node npm build 
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd src && npm install
    - run: cd src && npm run build --if-present
    - name: Save build artifact
      uses: actions/upload-artifact@v1
      with:
        name: build output (debug)
        path: dist   
    - run: cd src && npm run build --if-present
    - name: Save dist artifact
      uses: actions/upload-artifact@v1
      with:
        name: build output (dist)
        path: dist
    - name: Deploy to Firebase
      uses: lowply/deploy-firebase@v0.0.2
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: ${{ secrets.FIREBASE_APP_NAME }}
