name: Build and deploy with Node.js 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd src && npm install
    - run: cd src && npm run build --if-present
    - run: cd src && npm test
      env:
        CI: true
