name: Build with Node.js and deploy on push
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Node npm build 
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
    - run: cd src && npm install
    - run: cd src && npm run build --if-present
    - name: Save build artifact
      uses: actions/upload-artifact@v2
      with:
        name: build output (debug)
        path: dist   
    - run: cd src && npm run dist --if-present
    - name: Save dist artifact
      uses: actions/upload-artifact@v2
      with:
        name: build output (dist)
        path: dist
    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: ${{ secrets.FTP_URL }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PWD }}  
        server-dir: public_html/detect/  
        local-dir: ./dist/
        dangerous-clean-slate: true

